# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: “概率论与数理统计”课程笔记
author: 倪葎@DaSE-ECNU
logo: logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force
  timeout: 120
  allow_errors: true

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://LyuNi-ECNU.github.io/pr-webbook/intro.html
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: gh-pages  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  launch_buttons:
    thebe: true


parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - amsmath
    # - attrs_inline
    - colon_fence
    - deflist
    - dollarmath
    # - fieldlist
    - html_admonition
    # - html_image
    # - linkify
    # - replacements
    # - smartquotes
    # - strikethrough
    # - substitution
    - tasklist

sphinx:
  config:
    nb_execution_show_tb: True
    html_extra_path: [ './videos' ]
    html_js_files:
      - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    html_theme_options:
      launch_buttons:
        binderhub_url: "https://mybinder.org"
        thebe: true
      # 主题层面的仓库链接，必须指向你的仓库
      repository_url: https://github.com/LyuNi-ECNU/pr-webbook
      repository_branch: master
      use_edit_page_button: true
      use_issues_button: true
      use_repository_button: true
  extra_extensions:
    - sphinx_thebe
    - sphinx_proof
    - sphinx_design
    - sphinx_togglebutton
# https://sphinx-book-theme.readthedocs.io/en/stable/reference/extensions.html
# This is a extension which can be used to add sphinx-book-theme to the book.
# Marked by Deralive

# https://sphinx-thebe.readthedocs.io/en/latest/configure.html
# 将按钮嵌入至书中，允许用户在浏览器中运行代码

# https://diler-digitell.github.io/tutorial_jupyter_books/content/3_create/media.html
# This is a extension which can be used to add media files to the book.
# Marked by Deralive

# https://jupyterbook.org/en/stable/content/code-outputs.html
# This is a extension which can be used to add code outputs to the book.
# Marked by Deralive

